name             'owncloud'
maintainer       'David Pando'
maintainer_email 'david.pando@gmail.com'
license          'MIT'
description      'Installs/Configures owncloud'
long_description 'Installs/Configures owncloud'
version          '0.9.0'

depends 'nginx'
depends 'mysql'
depends 'database'
depends 'php'
depends 'php-fpm'
depends 'libarchive'
