default['owncloud']['version'] = '7.0.0'
default['owncloud']['download_url'] = "http://download.owncloud.org/community/owncloud-#{default['owncloud']['version']}.tar.bz2"
default['owncloud']['package_sha256_checksum'] = '9aca2aa0a0cd7b052e881c30ad6de25d135ec3f88a3920274f1be223b4cabedf'
default['owncloud']['server_names'] = %w{owncloud.example.com}
default['owncloud']['document_root'] = '/var/www/owncloud'
default['owncloud']['data_folder'] = '/var/www/owncloud/data'
default['owncloud']['adminlogin'] = 'admin'
default['owncloud']['adminpassword'] = ''
default['owncloud']['max_upload_size'] = '512M'
default['owncloud']['timeout'] = '1800' # For big files upload
default['owncloud']['enable_ssl'] = true
default['owncloud']['disable_trusted_domains'] = true
default['owncloud']['ssl_certificate'] = nil
default['owncloud']['ssl_certificate_key'] = nil
